# Generated by Django 3.2.9 on 2021-12-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=250, verbose_name='Detalles')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Nuevo', max_length=20, verbose_name='Estado')),
                ('tiporeparacion', models.CharField(choices=[('MOTOR', 'Motor'), ('CARROCERIA', 'Carroceria'), ('ELECTRICO', 'Electrico'), ('HIDRAULICO', 'Hidraulico')], default='MOTOR', max_length=20, verbose_name='Tipo Repación')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/vehiculo/', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
